FROM python:3.13-slim
RUN pip install --no-cache-dir mlflow
RUN mkdir -p /mlflow/artifacts
VOLUME /mlflow
ENV MLFLOW_SERVER_ALLOWED_HOSTS=*
EXPOSE 5000
CMD ["mlflow", "server", \
    "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
    "--artifacts-destination", "/mlflow/artifacts", \
    "--host", "0.0.0.0", \
    "--port", "5000"]
