FROM python:3.13-slim
WORKDIR /app
COPY pyproject.toml .
RUN pip install --no-cache-dir -e .
COPY src/ ./src/
COPY artifacts/ ./artifacts/
ENV MLFLOW_TRACKING_URI=http://mlflow-tracking:5000
EXPOSE 5001
CMD ["mlflow", "models", "serve", \
    "-m", "models:/cnn_model@Production", \
    "-p", "5001", \
    "--host", "0.0.0.0", \
    "--no-conda"]
